//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WrexhamFCMobileApp.WrexhamFCServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableNews", Namespace="http://schemas.datacontract.org/2004/07/WrexhamFCService")]
    public partial class TableNews : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AuthorField;
        
        private System.DateTime DateTimeField;
        
        private int IDNewsField;
        
        private string MessageField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDNews {
            get {
                return this.IDNewsField;
            }
            set {
                if ((this.IDNewsField.Equals(value) != true)) {
                    this.IDNewsField = value;
                    this.RaisePropertyChanged("IDNews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableNewsInfo", Namespace="http://schemas.datacontract.org/2004/07/WrexhamFCService")]
    public partial class TableNewsInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AuthorField;
        
        private System.DateTime DateTimeField;
        
        private int IDNewsField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDNews {
            get {
                return this.IDNewsField;
            }
            set {
                if ((this.IDNewsField.Equals(value) != true)) {
                    this.IDNewsField = value;
                    this.RaisePropertyChanged("IDNews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableMatchesInfo", Namespace="http://schemas.datacontract.org/2004/07/WrexhamFCService")]
    public partial class TableMatchesInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> AwayScoreField;
        
        private string AwayTeamField;
        
        private System.Nullable<int> HomeScoreField;
        
        private string HomeTeamField;
        
        private int IDMatchField;
        
        private System.Nullable<System.DateTime> MatchDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayScore {
            get {
                return this.AwayScoreField;
            }
            set {
                if ((this.AwayScoreField.Equals(value) != true)) {
                    this.AwayScoreField = value;
                    this.RaisePropertyChanged("AwayScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwayTeam {
            get {
                return this.AwayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamField, value) != true)) {
                    this.AwayTeamField = value;
                    this.RaisePropertyChanged("AwayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeScore {
            get {
                return this.HomeScoreField;
            }
            set {
                if ((this.HomeScoreField.Equals(value) != true)) {
                    this.HomeScoreField = value;
                    this.RaisePropertyChanged("HomeScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTeam {
            get {
                return this.HomeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamField, value) != true)) {
                    this.HomeTeamField = value;
                    this.RaisePropertyChanged("HomeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDMatch {
            get {
                return this.IDMatchField;
            }
            set {
                if ((this.IDMatchField.Equals(value) != true)) {
                    this.IDMatchField = value;
                    this.RaisePropertyChanged("IDMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MatchDate {
            get {
                return this.MatchDateField;
            }
            set {
                if ((this.MatchDateField.Equals(value) != true)) {
                    this.MatchDateField = value;
                    this.RaisePropertyChanged("MatchDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableMatches", Namespace="http://schemas.datacontract.org/2004/07/WrexhamFCService")]
    public partial class TableMatches : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> AwayCornerKicksField;
        
        private System.Nullable<int> AwayFoulsField;
        
        private System.Nullable<int> AwayFreeKicksField;
        
        private System.Nullable<int> AwayGoalAttemptsField;
        
        private System.Nullable<int> AwayGoalKeeperSavesField;
        
        private System.Nullable<int> AwayPossessionField;
        
        private System.Nullable<int> AwayScoreField;
        
        private System.Nullable<int> AwayShotsOffGoalField;
        
        private System.Nullable<int> AwayShotsOnGoalField;
        
        private string AwayTeamField;
        
        private System.Nullable<int> HomeCornerKicksField;
        
        private System.Nullable<int> HomeFoulsField;
        
        private System.Nullable<int> HomeFreeKicksField;
        
        private System.Nullable<int> HomeGoalAttemptsField;
        
        private System.Nullable<int> HomeGoalKeeperSavesField;
        
        private System.Nullable<int> HomePossessionField;
        
        private System.Nullable<int> HomeScoreField;
        
        private System.Nullable<int> HomeShotsOffGoalField;
        
        private System.Nullable<int> HomeShotsOnGoalField;
        
        private string HomeTeamField;
        
        private int IDMatchField;
        
        private System.Nullable<System.DateTime> MatchDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayCornerKicks {
            get {
                return this.AwayCornerKicksField;
            }
            set {
                if ((this.AwayCornerKicksField.Equals(value) != true)) {
                    this.AwayCornerKicksField = value;
                    this.RaisePropertyChanged("AwayCornerKicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayFouls {
            get {
                return this.AwayFoulsField;
            }
            set {
                if ((this.AwayFoulsField.Equals(value) != true)) {
                    this.AwayFoulsField = value;
                    this.RaisePropertyChanged("AwayFouls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayFreeKicks {
            get {
                return this.AwayFreeKicksField;
            }
            set {
                if ((this.AwayFreeKicksField.Equals(value) != true)) {
                    this.AwayFreeKicksField = value;
                    this.RaisePropertyChanged("AwayFreeKicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayGoalAttempts {
            get {
                return this.AwayGoalAttemptsField;
            }
            set {
                if ((this.AwayGoalAttemptsField.Equals(value) != true)) {
                    this.AwayGoalAttemptsField = value;
                    this.RaisePropertyChanged("AwayGoalAttempts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayGoalKeeperSaves {
            get {
                return this.AwayGoalKeeperSavesField;
            }
            set {
                if ((this.AwayGoalKeeperSavesField.Equals(value) != true)) {
                    this.AwayGoalKeeperSavesField = value;
                    this.RaisePropertyChanged("AwayGoalKeeperSaves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayPossession {
            get {
                return this.AwayPossessionField;
            }
            set {
                if ((this.AwayPossessionField.Equals(value) != true)) {
                    this.AwayPossessionField = value;
                    this.RaisePropertyChanged("AwayPossession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayScore {
            get {
                return this.AwayScoreField;
            }
            set {
                if ((this.AwayScoreField.Equals(value) != true)) {
                    this.AwayScoreField = value;
                    this.RaisePropertyChanged("AwayScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayShotsOffGoal {
            get {
                return this.AwayShotsOffGoalField;
            }
            set {
                if ((this.AwayShotsOffGoalField.Equals(value) != true)) {
                    this.AwayShotsOffGoalField = value;
                    this.RaisePropertyChanged("AwayShotsOffGoal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayShotsOnGoal {
            get {
                return this.AwayShotsOnGoalField;
            }
            set {
                if ((this.AwayShotsOnGoalField.Equals(value) != true)) {
                    this.AwayShotsOnGoalField = value;
                    this.RaisePropertyChanged("AwayShotsOnGoal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwayTeam {
            get {
                return this.AwayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamField, value) != true)) {
                    this.AwayTeamField = value;
                    this.RaisePropertyChanged("AwayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeCornerKicks {
            get {
                return this.HomeCornerKicksField;
            }
            set {
                if ((this.HomeCornerKicksField.Equals(value) != true)) {
                    this.HomeCornerKicksField = value;
                    this.RaisePropertyChanged("HomeCornerKicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeFouls {
            get {
                return this.HomeFoulsField;
            }
            set {
                if ((this.HomeFoulsField.Equals(value) != true)) {
                    this.HomeFoulsField = value;
                    this.RaisePropertyChanged("HomeFouls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeFreeKicks {
            get {
                return this.HomeFreeKicksField;
            }
            set {
                if ((this.HomeFreeKicksField.Equals(value) != true)) {
                    this.HomeFreeKicksField = value;
                    this.RaisePropertyChanged("HomeFreeKicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeGoalAttempts {
            get {
                return this.HomeGoalAttemptsField;
            }
            set {
                if ((this.HomeGoalAttemptsField.Equals(value) != true)) {
                    this.HomeGoalAttemptsField = value;
                    this.RaisePropertyChanged("HomeGoalAttempts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeGoalKeeperSaves {
            get {
                return this.HomeGoalKeeperSavesField;
            }
            set {
                if ((this.HomeGoalKeeperSavesField.Equals(value) != true)) {
                    this.HomeGoalKeeperSavesField = value;
                    this.RaisePropertyChanged("HomeGoalKeeperSaves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomePossession {
            get {
                return this.HomePossessionField;
            }
            set {
                if ((this.HomePossessionField.Equals(value) != true)) {
                    this.HomePossessionField = value;
                    this.RaisePropertyChanged("HomePossession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeScore {
            get {
                return this.HomeScoreField;
            }
            set {
                if ((this.HomeScoreField.Equals(value) != true)) {
                    this.HomeScoreField = value;
                    this.RaisePropertyChanged("HomeScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeShotsOffGoal {
            get {
                return this.HomeShotsOffGoalField;
            }
            set {
                if ((this.HomeShotsOffGoalField.Equals(value) != true)) {
                    this.HomeShotsOffGoalField = value;
                    this.RaisePropertyChanged("HomeShotsOffGoal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeShotsOnGoal {
            get {
                return this.HomeShotsOnGoalField;
            }
            set {
                if ((this.HomeShotsOnGoalField.Equals(value) != true)) {
                    this.HomeShotsOnGoalField = value;
                    this.RaisePropertyChanged("HomeShotsOnGoal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTeam {
            get {
                return this.HomeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamField, value) != true)) {
                    this.HomeTeamField = value;
                    this.RaisePropertyChanged("HomeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDMatch {
            get {
                return this.IDMatchField;
            }
            set {
                if ((this.IDMatchField.Equals(value) != true)) {
                    this.IDMatchField = value;
                    this.RaisePropertyChanged("IDMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MatchDate {
            get {
                return this.MatchDateField;
            }
            set {
                if ((this.MatchDateField.Equals(value) != true)) {
                    this.MatchDateField = value;
                    this.RaisePropertyChanged("MatchDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eventsByMatch", Namespace="http://schemas.datacontract.org/2004/07/WrexhamFCService")]
    public partial class eventsByMatch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AwayTeamField;
        
        private string EventNameField;
        
        private string HomeTeamField;
        
        private int IDEventField;
        
        private int IDMatchField;
        
        private System.Nullable<System.DateTime> MatchDateField;
        
        private System.Nullable<int> MinuteField;
        
        private string NameField;
        
        private int PlayerDressNumberField;
        
        private string TeamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwayTeam {
            get {
                return this.AwayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamField, value) != true)) {
                    this.AwayTeamField = value;
                    this.RaisePropertyChanged("AwayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTeam {
            get {
                return this.HomeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamField, value) != true)) {
                    this.HomeTeamField = value;
                    this.RaisePropertyChanged("HomeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEvent {
            get {
                return this.IDEventField;
            }
            set {
                if ((this.IDEventField.Equals(value) != true)) {
                    this.IDEventField = value;
                    this.RaisePropertyChanged("IDEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDMatch {
            get {
                return this.IDMatchField;
            }
            set {
                if ((this.IDMatchField.Equals(value) != true)) {
                    this.IDMatchField = value;
                    this.RaisePropertyChanged("IDMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MatchDate {
            get {
                return this.MatchDateField;
            }
            set {
                if ((this.MatchDateField.Equals(value) != true)) {
                    this.MatchDateField = value;
                    this.RaisePropertyChanged("MatchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Minute {
            get {
                return this.MinuteField;
            }
            set {
                if ((this.MinuteField.Equals(value) != true)) {
                    this.MinuteField = value;
                    this.RaisePropertyChanged("Minute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerDressNumber {
            get {
                return this.PlayerDressNumberField;
            }
            set {
                if ((this.PlayerDressNumberField.Equals(value) != true)) {
                    this.PlayerDressNumberField = value;
                    this.RaisePropertyChanged("PlayerDressNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team {
            get {
                return this.TeamField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamField, value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TablePlayers", Namespace="http://schemas.datacontract.org/2004/07/WrexhamFCService")]
    public partial class TablePlayers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> AgeField;
        
        private int DressNumber_ID_Field;
        
        private string FirstNameField;
        
        private System.Nullable<int> GoalsField;
        
        private System.Nullable<bool> InjuredField;
        
        private string LastNameField;
        
        private WrexhamFCMobileApp.WrexhamFCServiceReference.Binary PhotoField;
        
        private string PositionField;
        
        private System.Nullable<int> RedCardsField;
        
        private System.Nullable<int> YellowCardsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DressNumber_ID_ {
            get {
                return this.DressNumber_ID_Field;
            }
            set {
                if ((this.DressNumber_ID_Field.Equals(value) != true)) {
                    this.DressNumber_ID_Field = value;
                    this.RaisePropertyChanged("DressNumber_ID_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Goals {
            get {
                return this.GoalsField;
            }
            set {
                if ((this.GoalsField.Equals(value) != true)) {
                    this.GoalsField = value;
                    this.RaisePropertyChanged("Goals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Injured {
            get {
                return this.InjuredField;
            }
            set {
                if ((this.InjuredField.Equals(value) != true)) {
                    this.InjuredField = value;
                    this.RaisePropertyChanged("Injured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WrexhamFCMobileApp.WrexhamFCServiceReference.Binary Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RedCards {
            get {
                return this.RedCardsField;
            }
            set {
                if ((this.RedCardsField.Equals(value) != true)) {
                    this.RedCardsField = value;
                    this.RaisePropertyChanged("RedCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YellowCards {
            get {
                return this.YellowCardsField;
            }
            set {
                if ((this.YellowCardsField.Equals(value) != true)) {
                    this.YellowCardsField = value;
                    this.RaisePropertyChanged("YellowCards");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    public partial class Binary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] BytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableStandings", Namespace="http://schemas.datacontract.org/2004/07/WrexhamFCService")]
    public partial class TableStandings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> DrawsField;
        
        private System.Nullable<int> GoalsConcededField;
        
        private System.Nullable<int> GoalsScoredField;
        
        private System.Nullable<int> LossesField;
        
        private System.Nullable<int> MatchesPlayedField;
        
        private System.Nullable<int> PointsField;
        
        private string TeamField;
        
        private System.Nullable<int> WinsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Draws {
            get {
                return this.DrawsField;
            }
            set {
                if ((this.DrawsField.Equals(value) != true)) {
                    this.DrawsField = value;
                    this.RaisePropertyChanged("Draws");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GoalsConceded {
            get {
                return this.GoalsConcededField;
            }
            set {
                if ((this.GoalsConcededField.Equals(value) != true)) {
                    this.GoalsConcededField = value;
                    this.RaisePropertyChanged("GoalsConceded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GoalsScored {
            get {
                return this.GoalsScoredField;
            }
            set {
                if ((this.GoalsScoredField.Equals(value) != true)) {
                    this.GoalsScoredField = value;
                    this.RaisePropertyChanged("GoalsScored");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Losses {
            get {
                return this.LossesField;
            }
            set {
                if ((this.LossesField.Equals(value) != true)) {
                    this.LossesField = value;
                    this.RaisePropertyChanged("Losses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MatchesPlayed {
            get {
                return this.MatchesPlayedField;
            }
            set {
                if ((this.MatchesPlayedField.Equals(value) != true)) {
                    this.MatchesPlayedField = value;
                    this.RaisePropertyChanged("MatchesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team {
            get {
                return this.TeamField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamField, value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WrexhamFCServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAllNews", ReplyAction="http://tempuri.org/IService1/GetAllNewsResponse")]
        System.IAsyncResult BeginGetAllNews(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews> EndGetAllNews(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAllNewsInfo", ReplyAction="http://tempuri.org/IService1/GetAllNewsInfoResponse")]
        System.IAsyncResult BeginGetAllNewsInfo(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo> EndGetAllNewsInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNewsByID", ReplyAction="http://tempuri.org/IService1/GetNewsByIDResponse")]
        System.IAsyncResult BeginGetNewsByID(int IDNews, System.AsyncCallback callback, object asyncState);
        
        WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews EndGetNewsByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertNews", ReplyAction="http://tempuri.org/IService1/InsertNewsResponse")]
        System.IAsyncResult BeginInsertNews(WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews NewsObject, System.AsyncCallback callback, object asyncState);
        
        void EndInsertNews(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAllMatchesInfo", ReplyAction="http://tempuri.org/IService1/GetAllMatchesInfoResponse")]
        System.IAsyncResult BeginGetAllMatchesInfo(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo> EndGetAllMatchesInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetMatchByID", ReplyAction="http://tempuri.org/IService1/GetMatchByIDResponse")]
        System.IAsyncResult BeginGetMatchByID(int IDMatch, System.AsyncCallback callback, object asyncState);
        
        WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches EndGetMatchByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetMatchSummary", ReplyAction="http://tempuri.org/IService1/GetMatchSummaryResponse")]
        System.IAsyncResult BeginGetMatchSummary(int IDMatch, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch> EndGetMatchSummary(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAllPlayers", ReplyAction="http://tempuri.org/IService1/GetAllPlayersResponse")]
        System.IAsyncResult BeginGetAllPlayers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers> EndGetAllPlayers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetPlayerByID", ReplyAction="http://tempuri.org/IService1/GetPlayerByIDResponse")]
        System.IAsyncResult BeginGetPlayerByID(int IDPlayer, System.AsyncCallback callback, object asyncState);
        
        WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers EndGetPlayerByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetLeagueTable", ReplyAction="http://tempuri.org/IService1/GetLeagueTableResponse")]
        System.IAsyncResult BeginGetLeagueTable(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings> EndGetLeagueTable(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WrexhamFCMobileApp.WrexhamFCServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllNewsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllNewsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNewsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNewsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllMatchesInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllMatchesInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMatchByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMatchByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMatchSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMatchSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllPlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllPlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPlayerByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPlayerByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLeagueTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLeagueTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WrexhamFCMobileApp.WrexhamFCServiceReference.IService1>, WrexhamFCMobileApp.WrexhamFCServiceReference.IService1 {
        
        private BeginOperationDelegate onBeginGetAllNewsDelegate;
        
        private EndOperationDelegate onEndGetAllNewsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllNewsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllNewsInfoDelegate;
        
        private EndOperationDelegate onEndGetAllNewsInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllNewsInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNewsByIDDelegate;
        
        private EndOperationDelegate onEndGetNewsByIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetNewsByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertNewsDelegate;
        
        private EndOperationDelegate onEndInsertNewsDelegate;
        
        private System.Threading.SendOrPostCallback onInsertNewsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllMatchesInfoDelegate;
        
        private EndOperationDelegate onEndGetAllMatchesInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllMatchesInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMatchByIDDelegate;
        
        private EndOperationDelegate onEndGetMatchByIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetMatchByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMatchSummaryDelegate;
        
        private EndOperationDelegate onEndGetMatchSummaryDelegate;
        
        private System.Threading.SendOrPostCallback onGetMatchSummaryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllPlayersDelegate;
        
        private EndOperationDelegate onEndGetAllPlayersDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllPlayersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPlayerByIDDelegate;
        
        private EndOperationDelegate onEndGetPlayerByIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetPlayerByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLeagueTableDelegate;
        
        private EndOperationDelegate onEndGetLeagueTableDelegate;
        
        private System.Threading.SendOrPostCallback onGetLeagueTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllNewsCompletedEventArgs> GetAllNewsCompleted;
        
        public event System.EventHandler<GetAllNewsInfoCompletedEventArgs> GetAllNewsInfoCompleted;
        
        public event System.EventHandler<GetNewsByIDCompletedEventArgs> GetNewsByIDCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InsertNewsCompleted;
        
        public event System.EventHandler<GetAllMatchesInfoCompletedEventArgs> GetAllMatchesInfoCompleted;
        
        public event System.EventHandler<GetMatchByIDCompletedEventArgs> GetMatchByIDCompleted;
        
        public event System.EventHandler<GetMatchSummaryCompletedEventArgs> GetMatchSummaryCompleted;
        
        public event System.EventHandler<GetAllPlayersCompletedEventArgs> GetAllPlayersCompleted;
        
        public event System.EventHandler<GetPlayerByIDCompletedEventArgs> GetPlayerByIDCompleted;
        
        public event System.EventHandler<GetLeagueTableCompletedEventArgs> GetLeagueTableCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetAllNews(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllNews(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews> WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetAllNews(System.IAsyncResult result) {
            return base.Channel.EndGetAllNews(result);
        }
        
        private System.IAsyncResult OnBeginGetAllNews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetAllNews(callback, asyncState);
        }
        
        private object[] OnEndGetAllNews(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews> retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetAllNews(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllNewsCompleted(object state) {
            if ((this.GetAllNewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllNewsCompleted(this, new GetAllNewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllNewsAsync() {
            this.GetAllNewsAsync(null);
        }
        
        public void GetAllNewsAsync(object userState) {
            if ((this.onBeginGetAllNewsDelegate == null)) {
                this.onBeginGetAllNewsDelegate = new BeginOperationDelegate(this.OnBeginGetAllNews);
            }
            if ((this.onEndGetAllNewsDelegate == null)) {
                this.onEndGetAllNewsDelegate = new EndOperationDelegate(this.OnEndGetAllNews);
            }
            if ((this.onGetAllNewsCompletedDelegate == null)) {
                this.onGetAllNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllNewsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllNewsDelegate, null, this.onEndGetAllNewsDelegate, this.onGetAllNewsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetAllNewsInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllNewsInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo> WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetAllNewsInfo(System.IAsyncResult result) {
            return base.Channel.EndGetAllNewsInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetAllNewsInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetAllNewsInfo(callback, asyncState);
        }
        
        private object[] OnEndGetAllNewsInfo(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo> retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetAllNewsInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllNewsInfoCompleted(object state) {
            if ((this.GetAllNewsInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllNewsInfoCompleted(this, new GetAllNewsInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllNewsInfoAsync() {
            this.GetAllNewsInfoAsync(null);
        }
        
        public void GetAllNewsInfoAsync(object userState) {
            if ((this.onBeginGetAllNewsInfoDelegate == null)) {
                this.onBeginGetAllNewsInfoDelegate = new BeginOperationDelegate(this.OnBeginGetAllNewsInfo);
            }
            if ((this.onEndGetAllNewsInfoDelegate == null)) {
                this.onEndGetAllNewsInfoDelegate = new EndOperationDelegate(this.OnEndGetAllNewsInfo);
            }
            if ((this.onGetAllNewsInfoCompletedDelegate == null)) {
                this.onGetAllNewsInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllNewsInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllNewsInfoDelegate, null, this.onEndGetAllNewsInfoDelegate, this.onGetAllNewsInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetNewsByID(int IDNews, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNewsByID(IDNews, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetNewsByID(System.IAsyncResult result) {
            return base.Channel.EndGetNewsByID(result);
        }
        
        private System.IAsyncResult OnBeginGetNewsByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int IDNews = ((int)(inValues[0]));
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetNewsByID(IDNews, callback, asyncState);
        }
        
        private object[] OnEndGetNewsByID(System.IAsyncResult result) {
            WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetNewsByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNewsByIDCompleted(object state) {
            if ((this.GetNewsByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNewsByIDCompleted(this, new GetNewsByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNewsByIDAsync(int IDNews) {
            this.GetNewsByIDAsync(IDNews, null);
        }
        
        public void GetNewsByIDAsync(int IDNews, object userState) {
            if ((this.onBeginGetNewsByIDDelegate == null)) {
                this.onBeginGetNewsByIDDelegate = new BeginOperationDelegate(this.OnBeginGetNewsByID);
            }
            if ((this.onEndGetNewsByIDDelegate == null)) {
                this.onEndGetNewsByIDDelegate = new EndOperationDelegate(this.OnEndGetNewsByID);
            }
            if ((this.onGetNewsByIDCompletedDelegate == null)) {
                this.onGetNewsByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNewsByIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetNewsByIDDelegate, new object[] {
                        IDNews}, this.onEndGetNewsByIDDelegate, this.onGetNewsByIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginInsertNews(WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews NewsObject, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertNews(NewsObject, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndInsertNews(System.IAsyncResult result) {
            base.Channel.EndInsertNews(result);
        }
        
        private System.IAsyncResult OnBeginInsertNews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews NewsObject = ((WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews)(inValues[0]));
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginInsertNews(NewsObject, callback, asyncState);
        }
        
        private object[] OnEndInsertNews(System.IAsyncResult result) {
            ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndInsertNews(result);
            return null;
        }
        
        private void OnInsertNewsCompleted(object state) {
            if ((this.InsertNewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertNewsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertNewsAsync(WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews NewsObject) {
            this.InsertNewsAsync(NewsObject, null);
        }
        
        public void InsertNewsAsync(WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews NewsObject, object userState) {
            if ((this.onBeginInsertNewsDelegate == null)) {
                this.onBeginInsertNewsDelegate = new BeginOperationDelegate(this.OnBeginInsertNews);
            }
            if ((this.onEndInsertNewsDelegate == null)) {
                this.onEndInsertNewsDelegate = new EndOperationDelegate(this.OnEndInsertNews);
            }
            if ((this.onInsertNewsCompletedDelegate == null)) {
                this.onInsertNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertNewsCompleted);
            }
            base.InvokeAsync(this.onBeginInsertNewsDelegate, new object[] {
                        NewsObject}, this.onEndInsertNewsDelegate, this.onInsertNewsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetAllMatchesInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllMatchesInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo> WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetAllMatchesInfo(System.IAsyncResult result) {
            return base.Channel.EndGetAllMatchesInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetAllMatchesInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetAllMatchesInfo(callback, asyncState);
        }
        
        private object[] OnEndGetAllMatchesInfo(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo> retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetAllMatchesInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllMatchesInfoCompleted(object state) {
            if ((this.GetAllMatchesInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllMatchesInfoCompleted(this, new GetAllMatchesInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllMatchesInfoAsync() {
            this.GetAllMatchesInfoAsync(null);
        }
        
        public void GetAllMatchesInfoAsync(object userState) {
            if ((this.onBeginGetAllMatchesInfoDelegate == null)) {
                this.onBeginGetAllMatchesInfoDelegate = new BeginOperationDelegate(this.OnBeginGetAllMatchesInfo);
            }
            if ((this.onEndGetAllMatchesInfoDelegate == null)) {
                this.onEndGetAllMatchesInfoDelegate = new EndOperationDelegate(this.OnEndGetAllMatchesInfo);
            }
            if ((this.onGetAllMatchesInfoCompletedDelegate == null)) {
                this.onGetAllMatchesInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllMatchesInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllMatchesInfoDelegate, null, this.onEndGetAllMatchesInfoDelegate, this.onGetAllMatchesInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetMatchByID(int IDMatch, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMatchByID(IDMatch, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetMatchByID(System.IAsyncResult result) {
            return base.Channel.EndGetMatchByID(result);
        }
        
        private System.IAsyncResult OnBeginGetMatchByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int IDMatch = ((int)(inValues[0]));
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetMatchByID(IDMatch, callback, asyncState);
        }
        
        private object[] OnEndGetMatchByID(System.IAsyncResult result) {
            WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetMatchByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMatchByIDCompleted(object state) {
            if ((this.GetMatchByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMatchByIDCompleted(this, new GetMatchByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMatchByIDAsync(int IDMatch) {
            this.GetMatchByIDAsync(IDMatch, null);
        }
        
        public void GetMatchByIDAsync(int IDMatch, object userState) {
            if ((this.onBeginGetMatchByIDDelegate == null)) {
                this.onBeginGetMatchByIDDelegate = new BeginOperationDelegate(this.OnBeginGetMatchByID);
            }
            if ((this.onEndGetMatchByIDDelegate == null)) {
                this.onEndGetMatchByIDDelegate = new EndOperationDelegate(this.OnEndGetMatchByID);
            }
            if ((this.onGetMatchByIDCompletedDelegate == null)) {
                this.onGetMatchByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMatchByIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetMatchByIDDelegate, new object[] {
                        IDMatch}, this.onEndGetMatchByIDDelegate, this.onGetMatchByIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetMatchSummary(int IDMatch, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMatchSummary(IDMatch, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch> WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetMatchSummary(System.IAsyncResult result) {
            return base.Channel.EndGetMatchSummary(result);
        }
        
        private System.IAsyncResult OnBeginGetMatchSummary(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int IDMatch = ((int)(inValues[0]));
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetMatchSummary(IDMatch, callback, asyncState);
        }
        
        private object[] OnEndGetMatchSummary(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch> retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetMatchSummary(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMatchSummaryCompleted(object state) {
            if ((this.GetMatchSummaryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMatchSummaryCompleted(this, new GetMatchSummaryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMatchSummaryAsync(int IDMatch) {
            this.GetMatchSummaryAsync(IDMatch, null);
        }
        
        public void GetMatchSummaryAsync(int IDMatch, object userState) {
            if ((this.onBeginGetMatchSummaryDelegate == null)) {
                this.onBeginGetMatchSummaryDelegate = new BeginOperationDelegate(this.OnBeginGetMatchSummary);
            }
            if ((this.onEndGetMatchSummaryDelegate == null)) {
                this.onEndGetMatchSummaryDelegate = new EndOperationDelegate(this.OnEndGetMatchSummary);
            }
            if ((this.onGetMatchSummaryCompletedDelegate == null)) {
                this.onGetMatchSummaryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMatchSummaryCompleted);
            }
            base.InvokeAsync(this.onBeginGetMatchSummaryDelegate, new object[] {
                        IDMatch}, this.onEndGetMatchSummaryDelegate, this.onGetMatchSummaryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetAllPlayers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllPlayers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers> WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetAllPlayers(System.IAsyncResult result) {
            return base.Channel.EndGetAllPlayers(result);
        }
        
        private System.IAsyncResult OnBeginGetAllPlayers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetAllPlayers(callback, asyncState);
        }
        
        private object[] OnEndGetAllPlayers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers> retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetAllPlayers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllPlayersCompleted(object state) {
            if ((this.GetAllPlayersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllPlayersCompleted(this, new GetAllPlayersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllPlayersAsync() {
            this.GetAllPlayersAsync(null);
        }
        
        public void GetAllPlayersAsync(object userState) {
            if ((this.onBeginGetAllPlayersDelegate == null)) {
                this.onBeginGetAllPlayersDelegate = new BeginOperationDelegate(this.OnBeginGetAllPlayers);
            }
            if ((this.onEndGetAllPlayersDelegate == null)) {
                this.onEndGetAllPlayersDelegate = new EndOperationDelegate(this.OnEndGetAllPlayers);
            }
            if ((this.onGetAllPlayersCompletedDelegate == null)) {
                this.onGetAllPlayersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllPlayersCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllPlayersDelegate, null, this.onEndGetAllPlayersDelegate, this.onGetAllPlayersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetPlayerByID(int IDPlayer, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPlayerByID(IDPlayer, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetPlayerByID(System.IAsyncResult result) {
            return base.Channel.EndGetPlayerByID(result);
        }
        
        private System.IAsyncResult OnBeginGetPlayerByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int IDPlayer = ((int)(inValues[0]));
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetPlayerByID(IDPlayer, callback, asyncState);
        }
        
        private object[] OnEndGetPlayerByID(System.IAsyncResult result) {
            WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetPlayerByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPlayerByIDCompleted(object state) {
            if ((this.GetPlayerByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPlayerByIDCompleted(this, new GetPlayerByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPlayerByIDAsync(int IDPlayer) {
            this.GetPlayerByIDAsync(IDPlayer, null);
        }
        
        public void GetPlayerByIDAsync(int IDPlayer, object userState) {
            if ((this.onBeginGetPlayerByIDDelegate == null)) {
                this.onBeginGetPlayerByIDDelegate = new BeginOperationDelegate(this.OnBeginGetPlayerByID);
            }
            if ((this.onEndGetPlayerByIDDelegate == null)) {
                this.onEndGetPlayerByIDDelegate = new EndOperationDelegate(this.OnEndGetPlayerByID);
            }
            if ((this.onGetPlayerByIDCompletedDelegate == null)) {
                this.onGetPlayerByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPlayerByIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetPlayerByIDDelegate, new object[] {
                        IDPlayer}, this.onEndGetPlayerByIDDelegate, this.onGetPlayerByIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.BeginGetLeagueTable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLeagueTable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings> WrexhamFCMobileApp.WrexhamFCServiceReference.IService1.EndGetLeagueTable(System.IAsyncResult result) {
            return base.Channel.EndGetLeagueTable(result);
        }
        
        private System.IAsyncResult OnBeginGetLeagueTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).BeginGetLeagueTable(callback, asyncState);
        }
        
        private object[] OnEndGetLeagueTable(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings> retVal = ((WrexhamFCMobileApp.WrexhamFCServiceReference.IService1)(this)).EndGetLeagueTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLeagueTableCompleted(object state) {
            if ((this.GetLeagueTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLeagueTableCompleted(this, new GetLeagueTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLeagueTableAsync() {
            this.GetLeagueTableAsync(null);
        }
        
        public void GetLeagueTableAsync(object userState) {
            if ((this.onBeginGetLeagueTableDelegate == null)) {
                this.onBeginGetLeagueTableDelegate = new BeginOperationDelegate(this.OnBeginGetLeagueTable);
            }
            if ((this.onEndGetLeagueTableDelegate == null)) {
                this.onEndGetLeagueTableDelegate = new EndOperationDelegate(this.OnEndGetLeagueTable);
            }
            if ((this.onGetLeagueTableCompletedDelegate == null)) {
                this.onGetLeagueTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLeagueTableCompleted);
            }
            base.InvokeAsync(this.onBeginGetLeagueTableDelegate, null, this.onEndGetLeagueTableDelegate, this.onGetLeagueTableCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WrexhamFCMobileApp.WrexhamFCServiceReference.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<WrexhamFCMobileApp.WrexhamFCServiceReference.IService1>, WrexhamFCMobileApp.WrexhamFCServiceReference.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<WrexhamFCMobileApp.WrexhamFCServiceReference.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllNews(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllNews", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews> EndGetAllNews(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews> _result = ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews>)(base.EndInvoke("GetAllNews", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllNewsInfo(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllNewsInfo", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo> EndGetAllNewsInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo> _result = ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableNewsInfo>)(base.EndInvoke("GetAllNewsInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNewsByID(int IDNews, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = IDNews;
                System.IAsyncResult _result = base.BeginInvoke("GetNewsByID", _args, callback, asyncState);
                return _result;
            }
            
            public WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews EndGetNewsByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews _result = ((WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews)(base.EndInvoke("GetNewsByID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertNews(WrexhamFCMobileApp.WrexhamFCServiceReference.TableNews NewsObject, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = NewsObject;
                System.IAsyncResult _result = base.BeginInvoke("InsertNews", _args, callback, asyncState);
                return _result;
            }
            
            public void EndInsertNews(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("InsertNews", _args, result);
            }
            
            public System.IAsyncResult BeginGetAllMatchesInfo(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllMatchesInfo", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo> EndGetAllMatchesInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo> _result = ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatchesInfo>)(base.EndInvoke("GetAllMatchesInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMatchByID(int IDMatch, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = IDMatch;
                System.IAsyncResult _result = base.BeginInvoke("GetMatchByID", _args, callback, asyncState);
                return _result;
            }
            
            public WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches EndGetMatchByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches _result = ((WrexhamFCMobileApp.WrexhamFCServiceReference.TableMatches)(base.EndInvoke("GetMatchByID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMatchSummary(int IDMatch, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = IDMatch;
                System.IAsyncResult _result = base.BeginInvoke("GetMatchSummary", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch> EndGetMatchSummary(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch> _result = ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.eventsByMatch>)(base.EndInvoke("GetMatchSummary", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllPlayers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllPlayers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers> EndGetAllPlayers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers> _result = ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers>)(base.EndInvoke("GetAllPlayers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPlayerByID(int IDPlayer, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = IDPlayer;
                System.IAsyncResult _result = base.BeginInvoke("GetPlayerByID", _args, callback, asyncState);
                return _result;
            }
            
            public WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers EndGetPlayerByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers _result = ((WrexhamFCMobileApp.WrexhamFCServiceReference.TablePlayers)(base.EndInvoke("GetPlayerByID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLeagueTable(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetLeagueTable", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings> EndGetLeagueTable(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings> _result = ((System.Collections.ObjectModel.ObservableCollection<WrexhamFCMobileApp.WrexhamFCServiceReference.TableStandings>)(base.EndInvoke("GetLeagueTable", _args, result)));
                return _result;
            }
        }
    }
}
